version: "3.3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "7070:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=hello@hello.com
      - PGADMIN_DEFAULT_PASSWORD=password
volumes:
  postgres_data:
